services:
  - type: web
    name: decidata-website
    env: static
    buildCommand: echo "Static site - no build needed"
    staticPublishPath: ./
    domains:
      - decidata.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=86400
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
